blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/SawanoLab/adaptive-claude-agents/discussions
    about: Ask questions or discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/SawanoLab/adaptive-claude-agents/security/advisories/new
    about: Report a security vulnerability privately
